"""Add status column to healthcare_professionals

Revision ID: dd982cf06c2d
Revises: 08038cd96b21
Create Date: 2025-02-02 22:14:46.764174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd982cf06c2d'
down_revision = '08038cd96b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_professionals', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
